config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions", omniauth_callbacks: "users/omniauth_callbacks" }

  resources :comments

  resources :ratings

  resources :ingredients

  resources :recipes
  get '/recipes/ingredient_search', to: 'recipes#ingredient_search', as: 'ingredient_search'
  get 'show_recipe' => 'recipes#show_recipe'

  get '/patients/:id', to: 'patients#show', as: 'patient'

  resources :users

  get 'favourites' => 'favourites#index'
  post 'favourite_recipe' => 'favourites#create'
  delete 'favourite_recipe' => 'favourites#destroy'

  root 'recipes#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Chefly</title>
	<meta name="description" content="Discover new recipes">
	<meta name="keywords" content="Food,Recipes,Ingredients">

	<%= stylesheet_link_tag    'application', media: 'all' %>
	<%= javascript_include_tag 'application' %>
	<%= csrf_meta_tags %>

	<link href='http://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700' rel='stylesheet' type='text/css'>
	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
	<%= favicon_link_tag 'favicon.ico' %>


	<!-- Google Analytics -->
	<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	ga('create', 'UA-58881132-3', 'auto');
	ga('send', 'pageview');
	</script>

</head>
<body>
	<div class="info-overlay">
		<div class="info-container">
			<div class="info-text">
				<h3>Too Many Cooks</h3>
				<hr id="info-break"><br><br><br>
				<div class="info-body">
					Chefly was developed by Nic Haley and Phil Schwyter. We hope you like it. If you don't, feel free to send all your complaints to 'chefly.complaints@gmail.com'. No complaint is too big or too small.<br><br>

					Cheers,<br><br>

					Nic & Phil
				</div>
			</div><br>			
		</div>
	</div>
	<nav>
		<h3 id="logo"><%= link_to "Chefly", root_path %></h3>
		<h6 id="beta">beta</h6>
		<% if current_user %>
		<div class="sign-out">
			<div class="user-image"><%= image_tag current_user.avatar %><%= current_user.name.split(' ')[0] %></div>
			<ul class="menu">
				<hr>
				<li><%= link_to "Favourites", favourites_path %></li>
				<li><%= link_to "Sign out", destroy_user_session_path, :method => 'delete' %></li>
			</ul>
		</div>
		<% else %>
		<%= link_to user_omniauth_authorize_path(:facebook) do %>
		<div id="sign-in"><i class="fa fa-facebook"></i> Sign-in</div> 
		<% end %>
		<% end %>
	</nav>

	<%= yield %>
	
</body>
</html>